SOCIAL_AUTH_TWITTER_KEY = 'HrTouLrjnMACMHGt2DWjUdzxQ'
SOCIAL_AUTH_TWITTER_SECRET = '6Rd7bl3rfRIhGa5bL2tCMBhY7pCCvmdeolsb5eZTS8xzkepDn1'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'
